package com.max.tour.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.max.tour.bean.Sights;
import com.max.tour.bean.Admin;
import com.max.tour.bean.Picture;
import com.max.tour.bean.Route;
import com.max.tour.bean.User;
import com.max.tour.bean.Comment;
import com.max.tour.bean.Rate;

import com.max.tour.bean.greendao.SightsDao;
import com.max.tour.bean.greendao.AdminDao;
import com.max.tour.bean.greendao.PictureDao;
import com.max.tour.bean.greendao.RouteDao;
import com.max.tour.bean.greendao.UserDao;
import com.max.tour.bean.greendao.CommentDao;
import com.max.tour.bean.greendao.RateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sightsDaoConfig;
    private final DaoConfig adminDaoConfig;
    private final DaoConfig pictureDaoConfig;
    private final DaoConfig routeDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig rateDaoConfig;

    private final SightsDao sightsDao;
    private final AdminDao adminDao;
    private final PictureDao pictureDao;
    private final RouteDao routeDao;
    private final UserDao userDao;
    private final CommentDao commentDao;
    private final RateDao rateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sightsDaoConfig = daoConfigMap.get(SightsDao.class).clone();
        sightsDaoConfig.initIdentityScope(type);

        adminDaoConfig = daoConfigMap.get(AdminDao.class).clone();
        adminDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        routeDaoConfig = daoConfigMap.get(RouteDao.class).clone();
        routeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        rateDaoConfig = daoConfigMap.get(RateDao.class).clone();
        rateDaoConfig.initIdentityScope(type);

        sightsDao = new SightsDao(sightsDaoConfig, this);
        adminDao = new AdminDao(adminDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);
        routeDao = new RouteDao(routeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        rateDao = new RateDao(rateDaoConfig, this);

        registerDao(Sights.class, sightsDao);
        registerDao(Admin.class, adminDao);
        registerDao(Picture.class, pictureDao);
        registerDao(Route.class, routeDao);
        registerDao(User.class, userDao);
        registerDao(Comment.class, commentDao);
        registerDao(Rate.class, rateDao);
    }
    
    public void clear() {
        sightsDaoConfig.clearIdentityScope();
        adminDaoConfig.clearIdentityScope();
        pictureDaoConfig.clearIdentityScope();
        routeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        commentDaoConfig.clearIdentityScope();
        rateDaoConfig.clearIdentityScope();
    }

    public SightsDao getSightsDao() {
        return sightsDao;
    }

    public AdminDao getAdminDao() {
        return adminDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

    public RouteDao getRouteDao() {
        return routeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public RateDao getRateDao() {
        return rateDao;
    }

}
